### ISSUE TITLE
Duvida sobre o Projeto

### ISSUE THREAD

**Issue by NatanB4** [iCristianoSQL/jobs-grid#1]
Se eu entendi bem, projeto é pra listar todos as suas inscrições em possíveis vagas para acompanhar?

**Comment by iCristianoSQL** [comment]
> Se eu entendi bem, o projeto é pra listar todas as suas inscrições em possíveis vagas para acompanhar?

Exatamente, eu acabei de atualizar o Readme, o forte do sistema na minha opinião pessoal é o cadastro do linkedin do tech recruiter e do tech lead!

**Comment by NatanB4** [comment]
legal! ia contribuir com algo mas já esta finalizado né? hahahha

**Comment by iCristianoSQL** [comment]
> legal! ia contribuir com algo mas já esta finalizado né? hahahha

Que nada, de forma geral eu acredito que a estrutura do backend não está muito agradavel, sem falar que o css foi escrito as pressas :'(

pra piorar eu ignorei o SOLID, ou seja, tem muito trampo para fazer
